### ISSUE TITLE
How to pass params between view controllers in this library?

### ISSUE THREAD

**Issue by Gargo** [johnnieWa1ker/Transition#10]
Could you please post an example?

**Comment by johnnieWa1ker** [comment]
Hi! Will this example work?
https://github.com/johnnieWa1ker/Transition/tree/main/Example%20Apps/iOS

**Comment by Gargo** [comment]
@johnnieWa1ker this example works but you don't pass any data between modules/view controllers at all. They are fully separate.
Is it correct if I add `InputData` param in module `init` and in route push/present methods?

**Comment by johnnieWa1ker** [comment]
@Gargo sorry for the long answer! I was on vacation 🏖️)

Data transfer is carried out in any way convenient for you. For example, when using the VIPER architecture, this could be the Assembly class of the module. In any case, it does not depend on this library - it only determines how the screen is opened.

If this question is still relevant, I can add an example in the repository.
